### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by deepaksisodiya** [nsisodiya/react-kit#1]
I have follow the steps but not working for me. :)
<img width="626" alt="screen shot 2015-12-05 at 6 14 26 pm" src="https://cloud.githubusercontent.com/assets/3258231/11607814/0aee65ca-9b7c-11e5-8f01-9ee4751d4683.png">

**Comment by nsisodiya** [comment]
are you saying, u are unable to open  - http://localhost:8000/?m=Counter ?
