### ISSUE TITLE
Using promises in stores

### ISSUE THREAD

**Issue by tarunbhm** [nsisodiya/react-kit#5]
Thanks for providing this really helpful kit to kickstart react app.

I am using fetch api (https://github.com/github/fetch) for making api call from stores and it returns promise. Store action function returns before completing promise and storeBus.publish() is called right after returning from store action function therefore on calling store.getState() component gets previous state instead of new state.

Currently i am sending storeBus.publish("onChange") to store functions as an argument to solve this problem but i wanted to know if you have some other better solution or change in GenerateSingeltonStore.js.

**Comment by nsisodiya** [comment]
Hi Tarun ( @tarunbhm )
     Let me tell you best way to handle this case !!

1) Any change in Store should be done by publishing actions only. So, If you want server interaction than those interactions should be done via actions. actions will affect stores and store will redraw views.

Let me give exact example.
===========    READ  ==================

``` js
import GenerateSingletonStore from './../common/GenerateSingletonStore.js';
import dispatcher from '../../common/dispatcher.js';

export default GenerateSingletonStore({
    INIT: function (state) {
        state.list = [];
        state.listLoaded = false;
    },
    LOAD_TODO: function (state) {
        $.ajax({...}).then(function(list){
            dispatcher.publish("SET_TODO_LIST", list);
        });
    },
    SET_TODO_LIST: function (state, list) {
        state.list = list;
        state.listLoaded = true;
    }
});
```

`LOAD_TODO` is an action which basically do not affect state immediately, but start a AJAX call (same for fetch API). When Ajax call returns, it trigger another action which is `SET_TODO_LIST`.

`Store is Bank. State is Money. View and Server makes transactions on Bank`.

I hope, this is clear now. Server want to sent or update new data to Store. Only way to affect Store is dispatching actions. So when data is available on callback, just dispatch proper action for Setting up new Data.
I hope , it is clear now.
Please ask again if you are not clear.

Once again, If you use promises or simple callback or $.ajax or XMLHTTPRequest, it is same for all. in the callback, dispatch proper actions to set data.

**Comment by tarunbhm** [comment]
Thanks for the answer. Its clear and looks like the best way to handle this case. I think same can be extended to websocket connections as well. We can dispatch proper action on receiving message on websocket connection and elegantly manage application state.

**Comment by nsisodiya** [comment]
@tarunbhm 
   Yes ! You got the point ! You can change Store from websocket connection too. Server can trigger actions which can be directly published on main Dispatcher bus. 
    Underline idea is, Dispatcher is needed to update the Store and you can share dispatcher over anything. If server has access to dispatcher bus (via websocket etc) then server can change store directly from server. View always has access to dispatcher bus and it change store via trigger actions on dispatcher bus.
You can contribute to this repo but forking and sending pull request if you want !

Probably, you can write blog on your experiments on React and this react-kit.
